name: ORBmobile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2

  pointycastle: ^3.1.1
  basic_utils: ^3.1.0
  clipboard: ^0.1.3
  protobuf: ^2.0.0
  grpc: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true